apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app-with-node-server-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: html-app-with-node-server
  template:
    metadata:
      labels:
        app: html-app-with-node-server
    spec:
      containers:
      - name: html-app-with-node-server
        image: neetoci/html-app-with-node-server:1.0.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: html-app-with-node-server-service
spec:
  type: LoadBalancer
  selector:
    app: html-app-with-node-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000