apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-app
        image: neetoci/html-app:1.0.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: html-app-service
spec:
  type: LoadBalancer
  selector:
    app: html-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80